Fix logging to console when daemonized: always reset logging before each command received
Summary:
There were reports of Buck swallowing output when running through buckd. The core issue was that we changed the Python launcher script to close stdio file descriptors before launching buckd, but we failed to reset the logging infrastructure before each command (which would create a new `ConsoleHandler` connected to the new Nailgun client's stdio).

Test Plan:
Ran buck targets --show_rulekey //path/to/misconfigured:target before change. Co
nfirmed no exception:
  % buck targets --show_rulekey //path/to/misconfigured:target
  :::
  ::: '.nobuckcheck' file is present. Not updating buck.
  :::
  Using buckd.
  [-] PROCESSING BUCK FILES...FINISHED 1.2s
Applied diff, confirmed exception appeared:
  % buck targets --show_rulekey //Libraries/FBReactKit:JSResources
  :::
  ::: '.nobuckcheck' file is present. Not updating buck.
  :::
  Using buckd.
  [-] PROCESSING BUCK FILES...FINISHED 1.3s
  [2014-12-09 14:48:18.133][error][command:169a004e-06ab-4b1e-a573-36790d534aa1][tid:16][com.facebook.buck.cli.Main] Uncaught exception at top level
  java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.io.FileNotFoundException: (snip) (No such file or directory)
    at com.facebook.buck.util.DefaultFileHashCache.get(DefaultFileHashCache.java:
87)
    at com.facebook.buck.rules.RuleKey$Builder.setInputVal(RuleKey.java:306)
    at com.facebook.buck.rules.RuleKey$Builder.setInputs(RuleKey.java:292)
    at com.facebook.buck.rules.AbstractBuildRule.appendToRuleKey(AbstractBuildRule.java:146)
    at com.facebook.buck.rules.AbstractBuildRule.getRuleKeyPair(AbstractBuildRule.java:178)
    at com.facebook.buck.rules.AbstractBuildRule.getRuleKey(AbstractBuildRule.java:159)
    at com.facebook.buck.cli.TargetsCommand.doShowRules(TargetsCommand.java:358)
    at com.facebook.buck.cli.TargetsCommand.runCommandWithOptionsInternal(TargetsCommand.java:90)
    at com.facebook.buck.cli.TargetsCommand.runCommandWithOptionsInternal(TargetsCommand.java:1)
    at com.facebook.buck.cli.AbstractCommandRunner.runCommandWithOptions(AbstractCommandRunner.java:140)
    at com.facebook.buck.cli.AbstractCommandRunner.runCommand(AbstractCommandRunner.java:112)
    at com.facebook.buck.cli.Command.execute(Command.java:122)
    at com.facebook.buck.cli.Main.executeCommand(Main.java:656)
    at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:464)
    at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:956)
    at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1013)
    at com.facebook.buck.cli.Main.nailMain(Main.java:1042)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
  Caused by: java.util.concurrent.ExecutionException: java.io.FileNotFoundException: (snip) (No such file or directory)
    at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
    at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
    at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
    at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2320)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
    at com.facebook.buck.util.DefaultFileHashCache.get(DefaultFileHashCache.java:84)
    ... 21 more
  Caused by: java.io.FileNotFoundException: (snip) (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at com.google.common.io.Files$FileByteSource.openStream(Files.java:125)
    at com.google.common.io.Files$FileByteSource.openStream(Files.java:115)
    at com.google.common.io.ByteSource.copyTo(ByteSource.java:219)
    at com.google.common.io.ByteSource.hash(ByteSource.java:297)
    at com.facebook.buck.util.DefaultFileHashCache.getHashCode(DefaultFileHashCache.java:63)
    at com.facebook.buck.util.DefaultFileHashCache.access$0(DefaultFileHashCache.java:59)
    at com.facebook.buck.util.DefaultFileHashCache$1.load(DefaultFileHashCache.java:54)
    at com.facebook.buck.util.DefaultFileHashCache$1.load(DefaultFileHashCache.java:1)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
    ... 27 more

Ran `NO_BUCKD=1 buck targets ...` on misconfigured target and confirmed error appeared on console and logs were not rotated.