Add missing http libraries for buck publish command to work
Summary: Closes https://github.com/facebook/buck/pull/553

Test Plan:

  $ buck publish --remote-repo <foo> //:bar

isn't failing with:

  java.lang.NoClassDefFoundError: org/apache/http/client/HttpResponseException

Reviewed By: nayrmi, sdwilsh

fb-gh-sync-id: b3a7d9c