More explicit error messages when `ANDROID_SDK` etc. are set incorrectly.
Summary:
I accidentally had `ANDROID_SDK` set to the empty string.
This gave me a really confusing error message:

```
  java.lang.RuntimeException: /Users/bgertzfield/src/fbobjc was not a directory when trying to find sdk.dir
```

This clarifies the error message and adds tests.

Test Plan: Unit tests included. `ant unit` passes.