fix android_prebuilt_aar fail in buck project
Summary:
When running `buck project` which depends on `android_prebuilt_aar`, it will fail due to

```
com.facebook.buck.util.HumanReadableException: Rule for target '//testing#aar_classes_jar' could not be resolved.
```

The reason is `unzip_aar#aar_classes_jar` BuildRule is missing in the dependence graph. The fixing will be simply put it back

Closes https://github.com/facebook/buck/issues/219

Test Plan:
1. run in local, can not repro the failure
2. unit test to call `buck project`