Optionally treat assumptions as errors
Summary:
This is an extra diff on top of {D1443902}.  Use a `.buckconfig` (or more likely, `.buckconfig.local` option) to turn on the feature that considers an assumption violation as an error.

(We use assumption violations to indicate something went wrong, but not in a way that means the code-under-test is broken, so we still want to see what went wrong.)

Test Plan:
```
$ cat test/com/facebook/buck/junit/testdata/ignored_tests/.buckconfig
[test]
  assumptions-are-errors = no

$ ( cd test/com/facebook/buck/junit/testdata/ignored_tests/ && buck test --all --filter SomeAssumptionViolationsTest#assumptionFailureA)
[-] PARSING BUILD FILES...FINISHED 0.0s
[-] BUILDING...FINISHED 0.2s
Log:
TESTING SELECTED TESTS
ASSUME  <100ms  0 Passed   1 Skipped   0 Failed   com.example.SomeAssumptionViolationsTest
TESTS PASSED (with some assumption violations)

$ vim test/com/facebook/buck/junit/testdata/ignored_tests/.buckconfig # ...edit "no" to "yes"

$ ( cd test/com/facebook/buck/junit/testdata/ignored_tests/ && buck test --all --filter SomeAssumptionViolationsTest#assumptionFailureA)
[-] PARSING BUILD FILES...FINISHED 0.0s
[-] BUILDING...FINISHED 0.7s
Log:
TESTING SELECTED TESTS
ASSUME  <100ms  0 Passed   1 Skipped   0 Failed   com.example.SomeAssumptionViolationsTest
ASSUMPTION_VIOLATION assumptionFailureA: False is true!
org.junit.internal.AssumptionViolatedException: False is true!
        at org.junit.Assume.assumeTrue(Assume.java:59)
        at com.example.SomeAssumptionViolationsTest.assumptionFailureA(SomeAssumptionViolationsTest.java:27)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.junit.runners.Suite.runChild(Suite.java:127)
        at org.junit.runners.Suite.runChild(Suite.java:26)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
        at com.facebook.buck.junit.JUnitRunner.run(JUnitRunner.java:140)
        at com.facebook.buck.junit.JUnitRunner.main(JUnitRunner.java:424)

TESTS PASSED (with some assumption violations)
```