fix AetherUtil
Summary:
`org.eclipse.aether.repository.RemoteRepository.Builder#Builder( String id, String type, String url )` will use `id` (if provided) as a directory name. Since an URL is passed to `id` - it may contain colon which is illegal in windows paths.

Before fix PublishCommandIntegrationTest failed with an exception:
```
org.eclipse.aether.deployment.DeploymentException: Failed to retrieve remote metadata com.example:foo/maven-metadata.xml: Could not transfer metadata com.example:foo/maven-metadata.xml from/to http://127.0.0.1:53992/ (http://127.0.0.1:53992/): C:\Users\ilya\AppData\Local\Temp\junit6969619355233574830\com\example\foo\maven-metadata-http:\127.0.0.1:53992\.xml.part.lock (The filename, directory name, or volume label syntax is incorrect)
	at org.eclipse.aether.internal.impl.DefaultDeployer.upload(DefaultDeployer.java:447)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:329)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:245)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:413)
	at com.facebook.buck.maven.Publisher.publish(Publisher.java:254)
```

Now it passes

Test Plan: locally, CI

Reviewed By: Coneko

fbshipit-source-id: f3bfe21