Fail if main_class specified in java_binary doesn't exist
Summary:
Previously a typo in the `main_class` attribute of `java_binary` would
not be detected until one tried to run the built `jar`. This is something
we can detect when building the `jar`, however, so we might as well.

Test Plan:
Change a `main_class` attribute to be incorrect, then build. Observe error:
```
ERROR: Main class com.facebook.buck.java.ReportGenerator does not exist.
BUILD FAILED: //src/com/facebook/buck/java/coverage:report-generator failed with exit code 1:
jar
```